
services:
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: "mamie_cuisine"
      POSTGRES_PASSWORD: "test"
      POSTGRES_USER: "jerem"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "mamie_cuisine", "-U", "jerem"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025"  # Web interface
      - "1025:1025"  # SMTP service
    volumes:
      - mailpit_data:/data

volumes:
  mailpit_data: